---
# clone client from source
- name: Operating system dependencies
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - git
    - python-pip
    - python-virtualenv
    - dialog
    - libaugeas0
    - ca-certificates
  when: not ansible_distribution_release == 'stretch' and not ansible_distribution_release == 'bionic'
- name: Python cryptography module
  pip: name=cryptography
  when: not ansible_distribution_release == 'stretch' and not ansible_distribution_release == 'bionic'
- name: Letsencrypt Python client
  git:
    dest: /opt/certbot
    clone: yes
    update: yes
    repo: https://github.com/certbot/certbot
    force: yes
    version: '{{letsencrypt_certbot_version}}'
  when: not ansible_distribution_release == 'stretch' and not ansible_distribution_release == 'bionic'

# install client from package repo (available in debian stretch)
- name: Install Certbot
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - certbot
  when: ansible_distribution_release == 'stretch' or ansible_distribution_release == 'bionic'
